### ISSUE TITLE
Invalid attributes

### ISSUE THREAD

**Issue by deniswsrosa** [couchbaselabs/docs-devex#217]
inclusive_min and inclusive_max are invalid:

{
    "query":{
        "must_not":{
            "disjuncts":[
                {
                    "field": "free_breakfast",
                    "bool": false
                },
                {
                    "field": "ratings.Cleanliness",
                    "inclusive_min": 1,
                    "inclusive_max": 3
                }
            ]
        }
    }
}

at https://github.com/couchbaselabs/docs-devex/blob/54bd1d56d5bbb36f927b9d2cad3775723393efac/modules/search/examples/query-boolean.jsonc#L73-L89

**Comment by simon-dew** [comment]
Moved this to https://issues.couchbase.com/browse/DOC-12216
